### ISSUE TITLE
Drop `run-st`

### ISSUE THREAD

**Issue by WinstonHartnett** [byteverse/bytesmith#20]
The issue behind `run-st` [was closed](https://gitlab.haskell.org/ghc/ghc/-/issues/15127) and `run-st` holds back new `primitive-unlifted` versions. I'm assuming you can replace the specialized version of `runST` w/ `runST` now?

**Comment by chessai** [comment]
ping @andrewthad

**Comment by andrewthad** [comment]
I've confirmed that removing run-st does not cause a regression in https://github.com/byteverse/bytesmith/pull/33

I'll merge it soon.

**Comment by brianjosephmckeon** [comment]
Added to release 0.3.11.1 and published to Hackage.
https://github.com/byteverse/bytesmith/releases/tag/0.3.11.1
